services:
  # 1. MINIO - Object Storage Layer
  minio:
    image: minio/minio:latest
    container_name: tiki_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse_net
    restart: "no"

  minio-init:
    image: minio/mc:latest
    container_name: tiki_minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      /usr/bin/mc mb myminio/raw-data || true &&
      /usr/bin/mc mb myminio/lakehouse || true &&
      exit 0
      "
    networks:
      - lakehouse_net
    restart: "no"

  # 2. POSTGRES - Metastore & Superset Backend
  postgres:
    image: postgres:15
    container_name: tiki_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lakehouse_net
    restart: "no"

  # 3. TRINO - Distributed Query Engine
  trino:
    image: trinodb/trino:latest
    container_name: tiki_trino
    ports:
      - "8082:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - trino_metastore:/var/lib/trino/metastore
    networks:
      - lakehouse_net
    restart: "no"
    depends_on:
      - minio
      - postgres

  # 4. SUPERSET - Visualization (BI)
  superset:
    image: apache/superset:latest
    container_name: tiki_superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_LOAD_EXAMPLES: "no"
      SQLALCHEMY_DATABASE_URI: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      PYTHONPATH: "/app/pythonpath:/app/superset_home/.local/lib/python3.10/site-packages"
    networks:
      - lakehouse_net
    restart: "no"
    # Initialize the database and admin user
    entrypoint: >
      /bin/sh -c "
      pip install trino &&
      superset db upgrade &&
      superset fab create-admin --username ${SUPERSET_ADMIN_USER} --firstname Superset --lastname Admin --email admin@lakehouse.local --password ${SUPERSET_ADMIN_PASSWORD} &&
      superset init &&
      gunicorn -w 2 --timeout 120 -b 0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 'superset.app:create_app()'
      "
    depends_on:
      - postgres
      - trino

networks:
  lakehouse_net:
    driver: bridge

volumes:
  minio_data:
  pg_data:
  trino_metastore: