name: 'dbt_tiki'
version: '1.0.0'

profile: 'dbt_tiki'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_tiki:
    staging:
      +materialized: view
      +schema: bronze
    intermediate:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
      +on_table_exists: drop
