dbt_tiki:
  target: "{{ env_var('DBT_TARGET', 'local') }}"

  outputs:
    dev:
      type: trino
      method: none
      user: trino
      host: trino
      port: 8080
      database: iceberg
      schema: bronze
      threads: 4
      http_scheme: http
    local:
      type: trino
      method: none
      user: trino
      host: localhost
      port: 8080
      database: iceberg
      schema: bronze
      threads: 4
      http_scheme: http
